<?php
/* Teamup Calendar integration: shortcode + Customizer settings. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
function tcr199x_teamup_normalize_url( $url ){ $url = wp_unslash((string)$url); $url = html_entity_decode($url, ENT_QUOTES|ENT_HTML5); $url = trim($url); $url = trim($url, "\"'"); if($url===''){return '';} if(strpos($url,'//')===0){ $url='https:'.$url; } if(!preg_match('#^https?://#i',$url)){ if(preg_match('#^(?:[a-z0-9.-]+\.)?teamup\.com(?:/.*)?$#i',$url)){ $url='https://'.$url; } } return $url; }
function tcr199x_teamup_sanitize_view( $view ){ $view=strtolower((string)$view); $map=array('m'=>'m','month'=>'m','w'=>'w','week'=>'w','d'=>'d','day'=>'d','a'=>'a','agenda'=>'a'); return isset($map[$view])?$map[$view]:'m'; }
function tcr199x_teamup_build_embed_url( $base_url, $args=array() ){ $base_url=tcr199x_teamup_normalize_url($base_url); $base_url=esc_url_raw($base_url); if(empty($base_url)) return ''; $parts=wp_parse_url($base_url); if(empty($parts['host'])||strpos($parts['host'],'teamup.com')===false){ return ''; } $scheme=isset($parts['scheme'])?$parts['scheme']:'https'; $host=$parts['host']; $path=isset($parts['path'])?$parts['path']:''; $base=$scheme.'://'.$host.$path; $existing=array(); if(!empty($parts['query'])){ parse_str($parts['query'],$existing); } $allowed=array('view','showHeader','showTitle','showViewSelector','showSidepanel','showSearch','showMenu','lang','tz'); $merged=array(); foreach(array_merge($existing,$args) as $k=>$v){ if(in_array($k,$allowed,true)){ $merged[$k]=$v; } } return add_query_arg($merged,$base); }
function tcr199x_teamup_shortcode( $atts ){ $atts=shortcode_atts(array('url'=>get_theme_mod('tcr199x_teamup_url',''),'view'=>get_theme_mod('tcr199x_teamup_view','month'),'height'=>get_theme_mod('tcr199x_teamup_height',800),'sidebar'=>'0','title'=>'0','header'=>'0','view_selector'=>'0','search'=>'0','menu'=>'0','lang'=>'','tz'=>''),$atts,'retro_calendar'); $height=absint($atts['height']); if($height<200)$height=200; if($height>2000)$height=2000; $view=tcr199x_teamup_sanitize_view($atts['view']); $bool=function($v){ return ($v==='1'||$v===1||$v===true)?'1':'0'; }; $args=array('view'=>$view,'showHeader'=>$bool($atts['header']),'showTitle'=>$bool($atts['title']),'showViewSelector'=>$bool($atts['view_selector']),'showSidepanel'=>$bool($atts['sidebar']),'showSearch'=>$bool($atts['search']),'showMenu'=>$bool($atts['menu']),); $lang=preg_replace('/[^a-zA-Z\-]/','',(string)$atts['lang']); if(!empty($lang)){$args['lang']=$lang;} $tz=preg_replace('/[^A-Za-z0-9_\/\-\+]/','',(string)$atts['tz']); if(!empty($tz)){$args['tz']=$tz;} $src=tcr199x_teamup_build_embed_url($atts['url'],$args); if(empty($src)){ if(current_user_can('edit_theme_options')){ return '<div class="tcr199x-calendar tcr199x-calendar--missing">Teamup calendar is not configured. Set a shareable calendar URL in Appearance → Customize → Teamup Calendar, or pass url="" to the [retro_calendar] shortcode.</div>'; } return ''; } $title=esc_attr__('Teamup Calendar','trashchurch-retro-199x'); $html='<div class="tcr199x-calendar">'; $html.='<iframe src="'.esc_url($src).'" title="'.$title.'" width="100%" height="'.esc_attr($height).'" frameborder="0" scrolling="auto" loading="lazy"></iframe>'; $html.='</div>'; return $html; }
add_action('init',function(){ add_shortcode('retro_calendar','tcr199x_teamup_shortcode'); });
add_action('customize_register',function($wp_customize){ $wp_customize->add_section('tcr199x_teamup',array('title'=>__('Teamup Calendar','trashchurch-retro-199x'),'priority'=>70,'description'=>__('Embed a Teamup calendar using a shareable read-only URL.','trashchurch-retro-199x'),)); $wp_customize->add_setting('tcr199x_teamup_url',array('type'=>'theme_mod','sanitize_callback'=>'esc_url_raw','default'=>'',)); $wp_customize->add_control('tcr199x_teamup_url',array('label'=>__('Teamup Shareable URL','trashchurch-retro-199x'),'description'=>__('Example: https://teamup.com/ks123abcde or https://embed.teamup.com/ks123abcde','trashchurch-retro-199x'),'section'=>'tcr199x_teamup','type'=>'url',)); $wp_customize->add_setting('tcr199x_teamup_view',array('type'=>'theme_mod','sanitize_callback'=>'tcr199x_teamup_sanitize_view','default'=>'month',)); $wp_customize->add_control('tcr199x_teamup_view',array('label'=>__('Default View','trashchurch-retro-199x'),'section'=>'tcr199x_teamup','type'=>'select','choices'=>array('month'=>__('Month','trashchurch-retro-199x'),'week'=>__('Week','trashchurch-retro-199x'),'day'=>__('Day','trashchurch-retro-199x'),'agenda'=>__('Agenda','trashchurch-retro-199x'),),)); $wp_customize->add_setting('tcr199x_teamup_height',array('type'=>'theme_mod','sanitize_callback'=>'absint','default'=>800,)); $wp_customize->add_control('tcr199x_teamup_height',array('label'=>__('Calendar Height (px)','trashchurch-retro-199x'),'section'=>'tcr199x_teamup','type'=>'number','input_attrs'=>array('min'=>200,'max'=>2000,'step'=>10,),)); });
